## The order of the menus (e.g. menu.infra, menu.inspec, etc...) in the left nav menu
## is set by the menuOrder parameter below.
menuOrder = ["overview", "automate", "compliance",  "desktop", "habitat", "infra", "server", "inspec", "workstation", "effortless", "content", "release_notes", "legacy", "extra"]

enable_search = true
robots = ''

[chef-web-docs]
  gh_path = "https://github.com/chef/chef-web-docs/blob/master/content/"
