## The order of the menus (e.g. menu.infra, menu.inspec, etc...) in the left nav menu
## is set by the menuOrder parameter below.
menuOrder = [
  "overview",
  "360",
  "automate",
  "cloud",
  "desktop",
  "habitat",
  "infra",
  "server",
  "inspec",
  "workstation",
  "effortless",
  "supermarket",
  "release_notes",
  "legacy",
  "extra"
]

robots = ''
breadcrumbs = true

# sitemaps lists sitemaps that are indexed by the main sitemap layout.
# see:
# - layouts/_default/sitemap.xml
# - layouts/_default/home.sitemap-main.xml

sitemaps = [
  "https://docs.chef.io/sitemap-main.xml",
  "https://docs.chef.io/360/1.0/sitemap.xml",
  "https://docs.chef.io/360/1.1/sitemap.xml",
  "https://docs.chef.io/360/1.2/sitemap.xml",
  "https://docs.chef.io/360/1.3/sitemap.xml",
  "https://docs.chef.io/360/1.4/sitemap.xml",
  "https://docs.chef.io/360/1.5/sitemap.xml",
  "https://docs.chef.io/inspec/5.23/sitemap.xml",
  "https://docs.chef.io/inspec/6.8/sitemap.xml",
  "https://docs.chef.io/inspec/7.0/sitemap.xml",
  "https://docs.chef.io/inspec/resource_packs/sitemap.xml"
]

[chef-web-docs]
  gh_path = "https://github.com/chef/chef-web-docs/blob/main/content/"

[license-service]
gh_path = "https://github.com/chef/license-service/tree/main/docs-chef-io/content/"

######### Site search ##########
#
# This populates the site search page with search filter parameters.
#
# default_search_product_keys = The product search keys that are returned by search by default, ie when no product is selected in the search filters
#                               Use an empty string ("") for pages without a defined product.
#                               Include the latest/newest version of products that have muliple versions of documentation deployed.
#
# search.products.<PRODUCT> = A map/object/dictionary/table/whatever of products and their versions.
#                             This populates the left product search filter with product names and versions.
#
# name = The product name as it appears in the UI.
# product_key, product_version_key = The key used to filter results by in Swiftype API calls.
#                                    This product key is defined in the documatation frontmatter.
#                                    For example, the "habitat" key is defined in the docs.chef.io/habitat page frontmatter.
#                                    See here for example: https://github.com/habitat-sh/habitat/blob/main/components/docs-chef-io/content/habitat/_index.md?plain=1#L7
#
# search.products.<PRODUCT>.versions = A table of versions for a product.
#                                      Versions must be in order from newest/latest version to oldest and must be a string.
#
################################

[search]

default_search_product_keys = ["", "chef-360-saas", "chef-360-1.5", "automate", "desktop", "habitat", "client", "server", "inspec", "inspec-7.0", "saas", "supermarket", "workstation"]

[search.products]

[search.products.360]
name = "360 Platform"
product_key = "chef-360"

[[search.products.360.versions]]
name = "1.5"
product_version_key = "chef-360-1.5"

[[search.products.360.versions]]
name = "1.4"
product_version_key = "chef-360-1.4"

[[search.products.360.versions]]
name = "1.3"
product_version_key = "chef-360-1.3"

[[search.products.360.versions]]
name = "1.2"
product_version_key = "chef-360-1.2"

[[search.products.360.versions]]
name = "1.1"
product_version_key = "chef-360-1.1"

[[search.products.360.versions]]
name = "1.0"
product_version_key = "chef-360-1.0"

[search.products.360-saas]
name = "360 SaaS"
product_key = "chef-360-saas"

[search.products.automate]
name = "Automate"
product_key = "automate"

[search.products.desktop]
name = "Desktop"
product_key = "desktop"

[search.products.habitat]
name = "Habitat"
product_key = "habitat"

[search.products.infra_client]
name = "Infra Client"
product_key = "client"

[search.products.infra_server]
name = "Infra Server"
product_key = "server"

[search.products.inspec]
name = "InSpec"
product_key = "inspec"

[[search.products.inspec.versions]]
name = "7.0"
product_version_key = "inspec-7.0"

[[search.products.inspec.versions]]
name = "6.8"
product_version_key = "inspec-6.8"

[[search.products.inspec.versions]]
name = "5.23"
product_version_key = "inspec-5.23"

[search.products.saas]
name = "SaaS"
product_key = "saas"

[search.products.supermarket]
name = "Supermarket"
product_key = "supermarket"

[search.products.workstation]
name = "Workstation"
product_key = "workstation"

#######
#
# Settings for the link and image render hooks.
#
# See:
# - https://www.veriphor.com/articles/link-and-image-render-hooks/
# - https://gohugo.io/render-hooks/links/
# - https://gohugo.io/render-hooks/images/
#
# render_hooks.link.errorLevel
#       ignore (default), warning, or error (fails the build)
#
# render_hooks.link.highlightBroken
#        true or false (default). Adds `broken` class to link in development env
#
# render_hooks.image.errorLevel
#        ignore (default), warning, or error (fails the build)
#
#######

[render_hooks.link]
errorLevel = 'ignore'
highlightBroken = true

[render_hooks.image]
errorLevel = 'ignore'
