---
# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: docs-notify

github:
  delete_branch_on_merge: true
  release_branch:
    - master

pipelines:
  - verify:
      description: Pull Request validation tests
      public: true

subscriptions:
  # This will update version of the Chef product Hugo module
  # that is used to build the docs when that product is promoted to stable.
  - workload: artifact_published:stable:chef-workstation:*
    actions:
    - bash:.expeditor/update_hugo_modules_artifact_published.sh
  - workload: artifact_published:stable:inspec:*
    actions:
    - bash:.expeditor/update_hugo_modules_artifact_published.sh
  - workload: chef/automate:master_completed:project_promoted:chef/automate:master:acceptance:*
    actions:
    - bash:.expeditor/update_hugo_modules_project_promoted.sh
  - workload: habitat-sh/habitat:master_completed:project_promoted:habitat-sh/habitat:master:current:*
    actions:
    - bash:.expeditor/update_hugo_modules_project_promoted.sh
  - workload: pull_request_merged:chef/effortless:master:*
    actions:
    - bash:.expeditor/update_hugo_modules_pull_request_merged.sh:
        only_if_modified:
          - docs-chef-io/*
