slack:
  notify_channel: releng-notify

github:
  delete_branch_on_merge: true

pipelines:
  - verify:
      description: Pull Request validation tests
      definition: .expeditor/verify.pipeline.yml
  # - deploy/acceptance:
  #     description: Deploy changes to acceptance environment
  #     definition: .expeditor/deploy.pipeline.yml
  #     env:
  #       - ENVIRONMENT: acceptance