---
# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: docs-notify

github:
  delete_branch_on_merge: true
  release_branch:
    - master
    - hugo-migration

pipelines:
  - verify:
      description: Pull Request validation tests
      public: true
  - verify_private:
      description: Pull Request validation tests requiring access keys
  - deploy/acceptance:
      definition: .expeditor/deploy.pipeline.yml
      description: Deploy to chef-web-docs-acceptance.cd.chef.co
      env:
        - ENVIRONMENT: acceptance
  - deploy/production:
      definition: .expeditor/deploy.pipeline.yml
      description: Deploy to chef-web-docs-production.cd.chef.co (i.e. docs.chef.io)
      env:
        - ENVIRONMENT: production

merge_actions:
  - trigger_pipeline:deploy/acceptance:
      ignore_labels:
        - "Expeditor: Skip All"

promote:
  actions:
    - trigger_pipeline:deploy/production:
        only_if_conditions:
          - value_one: "{{target_channel}}"
            operator: equals
            value_two: stable
  channels:
    - acceptance    # chef-web-docs-acceptance.cd.chef.co / docs-acceptance.chef.io
    - stable        # chef-web-docs-production.cd.chef.co / docs.chef.io
